window.ALJAR = {
  brand: {
    name: "Al Jar Coffee",
    phone: "8 (985) 137-92-35",
    phone2: "8 (906) 767-47-25",
    phoneHref: "tel:+79851379235",
    email: "hello@aljar.ru",
  },
  subscribeDiscount: 0.1,
  weights: [
    { id: "250", label: "250 г", multiplier: 1 },
    { id: "500", label: "500 г", multiplier: 1.9 },
    { id: "1000", label: "1 кг", multiplier: 3.6 },
  ],
  grinds: [
    { id: "whole", label: "В зёрнах" },
    { id: "cezve", label: "Под турку" },
    { id: "french", label: "Френч-пресс" },
    { id: "filter", label: "Фильтр" },
  ],
  frequencies: [
    { id: "2", label: "Каждые 2 недели" },
    { id: "3", label: "Каждые 3 недели" },
    { id: "4", label: "Каждые 4 недели" },
  ],
  products: [
    {
      id: "pink-bourbon-mojiana",
      name: "Pink Bourbon & Mojiana",
      fullName: "Арабика 100% Pink Bourbon & Mojiana NY2 FC 16/18",
      price: 700,
      image: "img/bag-kraft.jpg",
      roast: "medium",
      roastLabel: "Средняя обжарка",
      origin: "Бразилия",
      region: "Можиана",
      process: "Натуральный / мытый",
      notes: "Шоколад, цитрус, карамель",
      acidity: 3,
      body: 4,
      sweetness: 4,
      method: "espresso",
      methodLabel: "Эспрессо",
      roastDate: "2026-08-18",
      species: "100% арабика",
      rating: 4.8,
      reviews: 18,
      featured: true,
    },
    {
      id: "pink-bourbon",
      name: "Pink Bourbon",
      fullName: "Арабика 100% Pink Bourbon",
      price: 1050,
      image: "img/bag-petrol.jpg",
      roast: "light",
      roastLabel: "Светлая обжарка",
      origin: "Колумбия",
      region: "Уила",
      process: "Мытый",
      notes: "Жасмин, ягоды, мёд",
      acidity: 4,
      body: 3,
      sweetness: 4,
      method: "filter",
      methodLabel: "Фильтр",
      roastDate: "2026-08-18",
      species: "100% арабика",
      rating: 4.9,
      reviews: 31,
      featured: true,
    },
    {
      id: "cattura",
      name: "Cattura",
      fullName: "Арабика 100% Cattura",
      price: 800,
      image: "img/bag-cream.jpg",
      roast: "medium",
      roastLabel: "Средняя обжарка",
      origin: "Бразилия",
      region: "Серрадо",
      process: "Натуральный",
      notes: "Какао, орех, карамель",
      acidity: 2,
      body: 5,
      sweetness: 3,
      method: "espresso",
      methodLabel: "Эспрессо",
      roastDate: "2026-08-17",
      species: "100% арабика",
      rating: 4.7,
      reviews: 12,
      featured: true,
    },
    {
      id: "cerrado",
      name: "Cerrado",
      fullName: "Арабика 100% Cerrado NY2 FC 16/18",
      price: 600,
      image: "img/bag-kraft.jpg",
      roast: "medium",
      roastLabel: "Средняя обжарка",
      origin: "Бразилия",
      region: "Серрадо",
      process: "Натуральный",
      notes: "Молочный шоколад, орех",
      acidity: 2,
      body: 4,
      sweetness: 4,
      method: "espresso",
      methodLabel: "Эспрессо",
      roastDate: "2026-08-17",
      species: "100% арабика",
      rating: 4.6,
      reviews: 22,
      featured: true,
    },
    {
      id: "geisha",
      name: "Geisha",
      fullName: "Арабика 100% Geisha",
      price: 1100,
      image: "img/bag-petrol.jpg",
      roast: "light",
      roastLabel: "Светлая обжарка",
      origin: "Эфиопия",
      region: "Сидамо",
      process: "Мытый",
      notes: "Жасмин, бергамот, персик",
      acidity: 5,
      body: 2,
      sweetness: 4,
      method: "filter",
      methodLabel: "Фильтр",
      roastDate: "2026-08-16",
      species: "100% арабика",
      rating: 5.0,
      reviews: 9,
      featured: false,
    },
    {
      id: "mojiana",
      name: "Mojiana",
      fullName: "Арабика 100% Mojiana NY2 FC 16/18",
      price: 620,
      image: "img/bag-cream.jpg",
      roast: "medium",
      roastLabel: "Средняя обжарка",
      origin: "Бразилия",
      region: "Можиана",
      process: "Натуральный",
      notes: "Шоколад, сухофрукты",
      acidity: 3,
      body: 4,
      sweetness: 3,
      method: "espresso",
      methodLabel: "Эспрессо",
      roastDate: "2026-08-16",
      species: "100% арабика",
      rating: 4.5,
      reviews: 14,
      featured: false,
    },
    {
      id: "sul-de-minas",
      name: "Sul De Minas",
      fullName: "Арабика 100% Sul De Minas NY2 FC 16/18",
      price: 575,
      image: "img/bag-kraft.jpg",
      roast: "medium",
      roastLabel: "Средняя обжарка",
      origin: "Бразилия",
      region: "Сул-ди-Минас",
      process: "Натуральный",
      notes: "Карамель, грецкий орех",
      acidity: 2,
      body: 4,
      sweetness: 3,
      method: "espresso",
      methodLabel: "Эспрессо",
      roastDate: "2026-08-15",
      species: "100% арабика",
      rating: 4.4,
      reviews: 11,
      featured: false,
    },
    {
      id: "sidamo",
      name: "Sidamo",
      fullName: "Арабика 100% Sidamo",
      price: 525,
      image: "img/bag-sage.jpg",
      roast: "light",
      roastLabel: "Светлая обжарка",
      origin: "Эфиопия",
      region: "Сидамо",
      process: "Мытый",
      notes: "Бергамот, цитрус, цветы",
      acidity: 4,
      body: 3,
      sweetness: 4,
      method: "filter",
      methodLabel: "Фильтр",
      roastDate: "2026-08-15",
      species: "100% арабика",
      rating: 4.7,
      reviews: 16,
      featured: false,
    },
    {
      id: "intensive",
      name: "Intensive",
      fullName: "Смесь Intensive",
      price: 525,
      image: "img/bag-petrol.jpg",
      roast: "dark",
      roastLabel: "Тёмная обжарка",
      origin: "Смесь",
      region: "Бразилия / Эфиопия",
      process: "Смешанный",
      notes: "Тёмный шоколад, специи",
      acidity: 2,
      body: 5,
      sweetness: 2,
      method: "cezve",
      methodLabel: "Турка",
      roastDate: "2026-08-14",
      species: "Смесь арабики",
      rating: 4.6,
      reviews: 27,
      featured: false,
    },
    {
      id: "ground-arabica",
      name: "Молотый арабика",
      fullName: "Кофе молотый арабика Al Jar Coffee",
      price: 550,
      image: "img/bag-kraft.jpg",
      roast: "medium",
      roastLabel: "Средняя обжарка",
      origin: "Смесь",
      region: "Ближний Восток / Бразилия",
      process: "Смешанный",
      notes: "Классика, шоколад, орех",
      acidity: 3,
      body: 4,
      sweetness: 3,
      method: "cezve",
      methodLabel: "Турка",
      roastDate: "2026-08-14",
      species: "100% арабика",
      rating: 4.5,
      reviews: 20,
      featured: false,
    },
  ],
  articles: [
    {
      id: "lebanese-coffee",
      title: "Ливанский кофе: ритуал гостеприимства",
      date: "12 августа 2026",
      excerpt: "Почему чашка кофе в Бейруте — это не напиток, а знак уважения. И как мы переносим этот ритуал в обжарку.",
      image: "img/dallah.jpg",
      tag: "Наследие",
    },
    {
      id: "how-to-brew-cezve",
      title: "Как заваривать кофе в турке",
      date: "4 августа 2026",
      excerpt: "Короткий гид: помол, вода, пенка. Для тех, кто хочет домашний ритуал без лишней мистики.",
      image: "img/brew.jpg",
      tag: "Приготовление",
    },
    {
      id: "roast-freshness",
      title: "Почему дата обжарки важнее сорта",
      date: "28 июля 2026",
      excerpt: "Свежесть — наш главный аргумент. Разбираем, что происходит с зерном на второй, десятый и тридцатый день.",
      image: "img/roaster.jpg",
      tag: "Обжарка",
    },
  ],
};
